/**
 * This file is generated by `stellar contract bindings typescript`.
 * Do not edit directly!
 */
import { Buffer } from "buffer";
// @ts-ignore generated file needs to import everything it *might* need
import { Address } from "@stellar/stellar-sdk";
// @ts-ignore generated file needs to import everything it *might* need
import {
  // @ts-ignore generated file needs to import everything it *might* need
  AssembledTransaction,
  // @ts-ignore generated file needs to import everything it *might* need
  Client as ContractClient,
  // @ts-ignore generated file needs to import everything it *might* need
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type {
  // @ts-ignore generated file needs to import everything it *might* need
  u32,
  // @ts-ignore generated file needs to import everything it *might* need
  i32,
  // @ts-ignore generated file needs to import everything it *might* need
  u64,
  // @ts-ignore generated file needs to import everything it *might* need
  i64,
  // @ts-ignore generated file needs to import everything it *might* need
  u128,
  // @ts-ignore generated file needs to import everything it *might* need
  i128,
  // @ts-ignore generated file needs to import everything it *might* need
  u256,
  // @ts-ignore generated file needs to import everything it *might* need
  i256,
  // @ts-ignore generated file needs to import everything it *might* need
  ClientOptions as ContractClientOptions,
  // @ts-ignore generated file needs to import everything it *might* need
  Option,
  // @ts-ignore generated file needs to import everything it *might* need
  Result,
  // @ts-ignore generated file needs to import everything it *might* need
  Typepoint,
  // @ts-ignore generated file needs to import everything it *might* need
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}
