#!/bin/sh

set -ex

cargo fmt --check || (cargo fmt && exit 1)

git diff-index --quiet HEAD --

cargo clippy --all -- -Dwarnings

cargo build
cargo test --all || (echo "might need to rebuild make build-snapshot" && exit 1)

echo '+cargo md-gen'
cargo md-gen
