#!/bin/sh

set -ex

make docs > /dev/null
make fmt > /dev/null

set +x
git diff --exit-code > /dev/null || (echo "\nERROR: Staged files were modified by hooks. Please review and stage the changes." && exit 1)
