name: 'Stale Issues / PRs'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # approx 9:30am daily

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          debug-only: false
          days-before-stale: 30
          days-before-close: 90
          stale-issue-message: 'This issue is stale because it has been assigned for 30 days with no activity. It will be closed in 90 days unless the stale label is removed, and the assignee is removed or updated.'
          stale-pr-message: 'This pull request is stale because it has been open for 30 days with no activity. It will be closed in 90 days unless the stale label is removed.'
          stale-issue-label: stale
          stale-pr-label: stale
          remove-stale-when-updated: true
          delete-branch: true
          include-only-assigned: true
